version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
#    environment:
#      POSTGRES_DB: jasne
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8080:8080"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jasne
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_JPA_HIBERNATE_DDL_AUTO: create
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  nginx:
    restart: unless-stopped
    env_file:
      .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
volumes:
  static_volume: {}
