version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8080:8080"

  nginx:
    restart: unless-stopped
    env_file:
      .env
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
volumes:
  static_volume: {}
